version: '3.9'

services:
  db-pedidos:
    container_name: db-pedidos
    hostname: db-pedidos
    image: postgres:15.6
    ports:
      - '8002:5432'
    expose:
      - 5432
    healthcheck:
      test: ['CMD', 'pg_isready -U ${DB_USER:-pguser} -d ${DB_NAME:-pedidos}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME:-pguser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pgpwd}
      POSTGRES_DB: ${DB_NAME:-pedidos}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    restart: always
    networks:
      - rms

  api-pedidos:
    container_name: api-pedidos
    hostname: api-pedidos
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    expose:
      - 3002
    env_file:
      - .env
    environment:
      DB_HOST: db-pedidos
      DB_PORT: 5432
      DB_USER: ${DB_USERNAME:-pguser}
      DB_PASSWORD: ${DB_PASSWORD:-pgpwd}
      DB_NAME: ${DB_NAME:-rms}
      DB_SSL: ${DB_SSL:-false}
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID:-}
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID:-}
      LOCALSTACK_ENDPOINT: http://localstack:4566
      NOME_FILA_NOVA_COBRANCA: ${NOME_FILA_NOVA_COBRANCA:-nova-cobranca}
      URL_FILA_NOVA_COBRANCA: http://localstack:4566/000000000000/nova-cobranca
      REGION_FILA_NOVA_COBRANCA: ${REGION_FILA_NOVA_COBRANCA:-us-east-1}
      NOME_FILA_COBRANCA_GERADA: ${NOME_FILA_COBRANCA_GERADA:-cobranca-gerada}
      URL_FILA_COBRANCA_GERADA: http://localstack:4566/000000000000/cobranca-gerada
      REGION_FILA_COBRANCA_GERADA: ${REGION_FILA_COBRANCA_GERADA:-us-east-1}
      NOME_FILA_FALHA_COBRANCA: ${NOME_FILA_FALHA_COBRANCA:-falha-cobranca}
      URL_FILA_FALHA_COBRANCA: http://localstack:4566/000000000000/falha-cobranca
      REGION_FILA_FALHA_COBRANCA: ${REGION_FILA_FALHA_COBRANCA:-us-east-1}
    restart: always
    networks:
      - rms
    depends_on:
      - db-pedidos
      - localstack

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:3.5.0
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=sqs
    volumes:
      - "./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"  # ready hook
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    networks:
      - rms

networks:
  rms:
    name: rms_network
    driver: bridge

volumes:
  postgres:
