apiVersion: v1
kind: Service
metadata:
  name: rms-api-pedidos
  namespace: rms
  labels:
    app: rms-api-pedidos
spec:
  selector:
    app: rms-api-pedidos
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80 # Porta no Load Balancer
      targetPort: 3002 # Porta do Pod