apiVersion: v1
kind: ConfigMap
metadata:
  name: rms-api-pedidos-config
  namespace: rms
  labels:
    app: rms-api-pedidos
data:
  DB_NAME: "pedidos"
  DB_SSL: "false"
  URL_API_PAGAMENTOS: "http://rms-api-pagamentos.rms.svc.cluster.local:80/pedido"