apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-api-pedidos
  namespace: rms
spec:
  provider: aws
  secretObjects:
    - secretName: db-pedidos-secret # Nome do Secret que será montado automaticamente contendo os segredos do AWS Secrets Manager
      type: Opaque
      data:
        - objectName: host
          key: host
        - objectName: port
          key: port
        - objectName: username
          key: username
        - objectName: password
          key: password
    - secretName: cognito-secret # Nome do Secret que será montado automaticamente contendo os segredos do AWS Secrets Manager
      type: Opaque
      data:
        - objectName: COGNITO_USER_POOL_ID
          key: COGNITO_USER_POOL_ID
        - objectName: COGNITO_CLIENT_ID
          key: COGNITO_CLIENT_ID
  parameters:
    # Informe abaixo no campo objectName os nomes dos Segredos do AWS Secrets Manager que deseja acessar.
    # Certifique-se de que as Keys declaradas abaixo existem e estão preenchidas na AWS, caso contrário receberá o erro "Failed to fetch secret from all regions"
    objects: |
      - objectName: "prod/pedidos/Postgresql"
        objectType: "secretsmanager"
        jmesPath:
          - path: "host"
            objectAlias: "host"
          - path: "port"
            objectAlias: "port"
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
      - objectName: "prod/RMS/Cognito"
        objectType: "secretsmanager"
        jmesPath:
          - path: "COGNITO_USER_POOL_ID"
            objectAlias: "COGNITO_USER_POOL_ID"
          - path: "COGNITO_CLIENT_ID"
            objectAlias: "COGNITO_CLIENT_ID"
